export const Users = [
  {
    id:1,
    profilePicture: "/src/assets/person/person1.jpeg",
    username: "Linda Norton",
  },
  {
    id:2,
    profilePicture: "/src/assets/person/person2.jpeg",
    username: "Albino guy",
  },
  {
    id:3,
    profilePicture: "/src/assets/person/person3.jpeg",
    username: "Candy Fletcher",
  },
  {
    id:4,
    profilePicture: "/src/assets/person/person4.jpeg",
    username: "Chelsea Scott",
  },
  {
    id:5,
    profilePicture: "/src/assets/person/person5.jpeg",
    username: "Linda White",
  },
  {
    id:6,
    profilePicture: "/src/assets/person/person6.jpeg",
    username: "Braids Norton",
  },
  {
    id:7,
    profilePicture: "/src/assets/person/person7.jpeg",
    username: "Model ??",
  },
  {
    id:8,
    profilePicture: "/src/assets/person/person8.jpeg",
    username: "Curly chap",
  },
  {
    id:9,
    profilePicture: "/src/assets/person/person9.jpeg",
    username: "Gary Neville",
  },
  {
    id:10,
    profilePicture: "/src/assets/person/person10.jpeg",
    username: "Kristen Tomas",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/src/assets/post/post1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/src/assets/post/post2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/src/assets/post/post3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/src/assets/post/post4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/src/assets/post/post5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/src/assets/post/post6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/src/assets/post/post7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/src/assets/post/post8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "/src/assets/post/post9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/src/assets/post/post10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
